export { default as Layout } from "./Layout"
export { default as Navbar } from "./Navbar"
export { default as Vanta } from "./Vanta"
export { default as Header } from "./Header"
export { default as Announcement } from "./Announcement"
export { default as Iet } from "./IET"
export { default as Achievements } from "./Achievements"
export { default as Footer } from "./Footer"
export { default as About } from "./About"
export { default as Team } from "./Team"
export { default as Testimonials } from "./Testimonials"

